<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>SchoolManagementApplciation</RootNamespace>
    <AssemblyName>SchoolManagementApplciation</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>1459676203_graduation.ico</ApplicationIcon>
    <StartupObject>SchoolManagementApplciation.Program</StartupObject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="AddService.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="AddService.Designer.cs">
      <DependentUpon>AddService.cs</DependentUpon>
    </Compile>
    <Compile Include="AddStudent.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="AddStudent.Designer.cs">
      <DependentUpon>AddStudent.cs</DependentUpon>
    </Compile>
    <Compile Include="AddTeacher.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="AddTeacher.Designer.cs">
      <DependentUpon>AddTeacher.cs</DependentUpon>
    </Compile>
    <Compile Include="AssociateService.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="AssociateService.Designer.cs">
      <DependentUpon>AssociateService.cs</DependentUpon>
    </Compile>
    <Compile Include="Edits.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Edits.Designer.cs">
      <DependentUpon>Edits.cs</DependentUpon>
    </Compile>
    <Compile Include="EnterMarkss.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="EnterMarkss.Designer.cs">
      <DependentUpon>EnterMarkss.cs</DependentUpon>
    </Compile>
    <Compile Include="feesda.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="feesda.Designer.cs">
      <DependentUpon>feesda.cs</DependentUpon>
    </Compile>
    <Compile Include="FeesStructures.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="FeesStructures.Designer.cs">
      <DependentUpon>FeesStructures.cs</DependentUpon>
    </Compile>
    <Compile Include="LoginDialog.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="LoginDialog.Designer.cs">
      <DependentUpon>LoginDialog.cs</DependentUpon>
    </Compile>
    <Compile Include="MainInterface.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="MainInterface.Designer.cs">
      <DependentUpon>MainInterface.cs</DependentUpon>
    </Compile>
    <Compile Include="ManageServices.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="ManageServices.Designer.cs">
      <DependentUpon>ManageServices.cs</DependentUpon>
    </Compile>
    <Compile Include="ManageStudents.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="ManageStudents.Designer.cs">
      <DependentUpon>ManageStudents.cs</DependentUpon>
    </Compile>
    <Compile Include="ManageTeacher.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="ManageTeacher.Designer.cs">
      <DependentUpon>ManageTeacher.cs</DependentUpon>
    </Compile>
    <Compile Include="ManageUsers.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="ManageUsers.Designer.cs">
      <DependentUpon>ManageUsers.cs</DependentUpon>
    </Compile>
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Selection.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Selection.Designer.cs">
      <DependentUpon>Selection.cs</DependentUpon>
    </Compile>
    <Compile Include="Services.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Services.Designer.cs">
      <DependentUpon>Services.cs</DependentUpon>
    </Compile>
    <Compile Include="SqlControl.cs" />
    <Compile Include="StudentAt.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="StudentAt.Designer.cs">
      <DependentUpon>StudentAt.cs</DependentUpon>
    </Compile>
    <Compile Include="Studentsdetailedlist.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Studentsdetailedlist.Designer.cs">
      <DependentUpon>Studentsdetailedlist.cs</DependentUpon>
    </Compile>
    <Compile Include="TeacherDetailedAttendance.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="TeacherDetailedAttendance.Designer.cs">
      <DependentUpon>TeacherDetailedAttendance.cs</DependentUpon>
    </Compile>
    <Compile Include="TeachersAttendance.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="TeachersAttendance.Designer.cs">
      <DependentUpon>TeachersAttendance.cs</DependentUpon>
    </Compile>
    <Compile Include="Utils.cs" />
    <Compile Include="WelcomeScreen.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="WelcomeScreen.Designer.cs">
      <DependentUpon>WelcomeScreen.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Include="AddService.resx">
      <DependentUpon>AddService.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="AddStudent.resx">
      <DependentUpon>AddStudent.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="AddTeacher.resx">
      <DependentUpon>AddTeacher.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="AssociateService.resx">
      <DependentUpon>AssociateService.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Edits.resx">
      <DependentUpon>Edits.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="EnterMarkss.resx">
      <DependentUpon>EnterMarkss.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="feesda.resx">
      <DependentUpon>feesda.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="FeesStructures.resx">
      <DependentUpon>FeesStructures.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="LoginDialog.resx">
      <DependentUpon>LoginDialog.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="MainInterface.resx">
      <DependentUpon>MainInterface.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="ManageServices.resx">
      <DependentUpon>ManageServices.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="ManageStudents.resx">
      <DependentUpon>ManageStudents.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="ManageTeacher.resx">
      <DependentUpon>ManageTeacher.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="ManageUsers.resx">
      <DependentUpon>ManageUsers.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <EmbeddedResource Include="Selection.resx">
      <DependentUpon>Selection.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Services.resx">
      <DependentUpon>Services.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="StudentAt.resx">
      <DependentUpon>StudentAt.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Studentsdetailedlist.resx">
      <DependentUpon>Studentsdetailedlist.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="TeacherDetailedAttendance.resx">
      <DependentUpon>TeacherDetailedAttendance.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="TeachersAttendance.resx">
      <DependentUpon>TeachersAttendance.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="WelcomeScreen.resx">
      <DependentUpon>WelcomeScreen.cs</DependentUpon>
    </EmbeddedResource>
    <None Include="App.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Include="1459676203_graduation.ico" />
    <None Include="Resources\gear.jpg" />
    <None Include="Resources\1459676046_floppy-disk.ico" />
    <None Include="Resources\1459676203_graduation.ico" />
    <None Include="Resources\1459676288_cmyk-04.ico" />
    <None Include="Resources\1459676300_Login Manager.ico" />
    <None Include="Resources\1459676422_Teacher-male-24.ico" />
    <None Include="Resources\1459676477_graduation.ico" />
    <None Include="Resources\1459676519_icon-help-circled.ico" />
    <None Include="Resources\1459676551_add_user.ico" />
    <None Include="Resources\1459676551_add_user1.ico" />
    <None Include="Resources\1459676565_user-id.ico" />
    <None Include="Resources\1459676723_Test-paper-24.ico" />
    <None Include="Resources\1459676753_vector_65_04.ico" />
    <None Include="Resources\1459676787_19.ico" />
    <None Include="Resources\1459676815_system-log-out.ico" />
    <None Include="Resources\1459676906_DeleteRed.ico" />
    <None Include="Resources\attts.jpg" />
    <None Include="Resources\Bill Heading.jpg" />
    <None Include="Resources\dash.jpg" />
    <None Include="Resources\dashstu.jpg" />
    <None Include="Resources\exting.jpg" />
    <None Include="Resources\fex.jpg" />
    <None Include="Resources\gradess.jpg" />
    <None Include="Resources\helpy.jpg" />
    <None Include="Resources\infosis.jpg" />
    <None Include="Resources\Lakshmi 2.jpg" />
    <None Include="Resources\linkss.jpg" />
    <None Include="Resources\logggg.jpg" />
    <None Include="Resources\managestu.png" />
    <None Include="Resources\newflex.bmp" />
    <None Include="Resources\tea.jpg" />
    <None Include="Resources\wallet.jpg" />
    <None Include="Resources\gear_icon.png" />
  </ItemGroup>

</Project>
